baseURL = "https://nickburaglio.com/"
languageCode = "en-us"
title = "Nick Buraglio......com"
theme = "hugo-theme-console"
disqusShortname = "nickburaglio"

[Params]
    headline = "NickBuraglio.com"
    description = "Random junk that updates infrequently"
    github = "https://github.com/buraglio"
    linkedin = "https://linkedin.com/in/buraglio/"
    email = "my firstname at my lastime dot com"

  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "post/"
  url = "post/"



[permalinks]
  posts = "/:year/:month/:title/"

