baseURL = "https://nickburaglio.com/"
languageCode = "en-us"
title = "Nick Buraglio......com"
theme = "hugo-minimalist-spa"
disqusShortname = "nickburaglio"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "NickBuraglio.com"
    description = "Random junk that updates infrequently"
    github = "https://github.com/buraglio"
    linkedin = "https://linkedin.com/in/buraglio/"
    twitter = "https://twitter.com/forwardingplane"
    facebook = "https://www.facebook.com/buraglio"
    email = "my firstname at my lastime dot com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"
[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"

  [[menu.main]]
    identifier = "post"
    name = "posts"
    url = "/posts"

[permalinks]
  posts = "/:year/:month/:title/"

